export type CharacterSet = {
  name: string;
  characters: readonly string[];
};

export const CHARACTER_SETS: CharacterSet[] = [
  {
    name: "Montsouris",
    characters: [
      "Anna",
      "Audrey",
      "Benbouaza",
      "Bernateau",
      "Carla",
      "Catherine",
      "Chris",
      "Claire",
      "Elise",
      "Florent",
      "Jean-Michel",
      "Laetitia",
      "Leila",
      "Lucile",
      "Marie",
      "Mathilde",
      "Michele",
      "Mongin",
      "Nathalie",
      "Pauline",
      "Potyrcha",
      "Quitterie",
      "Vic",
      "Victor",
    ] as const,
  },
  {
    name: "Routeurs",
    characters: [
      "Adrien",
      "Amélie",
      "Baptiste",
      "Camille",
      "Damien",
      "Émilie",
      "Fabien",
      "Gaëlle",
      "Hugo",
      "Inès",
      "Julien",
      "Karine",
      "Laurent",
      "Manon",
      "Nicolas",
      "Ophélie",
      "Pierre",
      "Roxane",
      "Sébastien",
      "Thibault",
      "Ugo",
      "Valérie",
      "Xavier",
      "Zoé",
    ] as const,
  },
];
