export type CharacterSet = {
  name: string;
  characters: readonly string[];
};

export const CHARACTER_SETS: CharacterSet[] = [
  {
    name: "Routeurs",
    characters: [
      "Florent",
      "Juliette",
      "Dimitri",
      "Pierre-Antoine",
      "Camille",
      "Manon",
      "Adrien",
      "Audrey",
      "Marcel",
      "Cedric",
      "Pierre",
      "Isaline",
      "Maxime",
      "Adelie",
      "Alexandre",
      "Yann",
      "Koya",
      "Elisabeth",
    ] as const,
  },
  {
    name: "Montsouris",
    characters: [
      "Aifa",
      "Alice",
      "Anna",
      "Carla",
      "Catherine",
      "Chris",
      "Claire",
      "Elise",
      "Grace",
      "Florent",
      "Jean-Michel",
      "Laetitia",
      "Lucile",
      "Marie",
      "Mathilde",
      "Maude",
      "Michele",
      "Pascale",
      "Pauline",
      "Quitterie",
      "Vic",
      "Victor",
      "Xavier",
      "Élo",
    ] as const,
  },
  {
    name: "Soignants",
    characters: [
      "Delphine",
      "Bénédicte",
      "Directeur",
      "Mongin",
      "Bernateau",
      "Lafaye",
      "Fontaine",
      "Potyrcha",
      "Benbouaza",
      "Leïla",
      "Lou",
      "Kenza",
      "Gwen",
      "Agathe",
      "Audrey",
      "Odile",
      "Florise",
      "Nadine",
      "Julien",
      "Mathilde",
      "Florian",
      "Peinture",
      "Écriture",
      "Couture",
    ] as const,
  },
];
